In [1]:
import pandas as pd

In [11]:
p_val = pd.read_csv("p_val.csv")

In [12]:
p_val

,Cancer,A1BG,A1CF,A2M,A2ML1,A4GALT,AAAS,AACS,AADAC,AADAT,...,ZSWIM9,ZW10,ZWILCH,ZWINT,ZXDA,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
0,ccrcc,0.008435,0.001958,0.061198,NaN,0.347296,0.767248,1.477092e-01,0.081185,0.370717,...,NaN,0.069946,1.166079e-01,2.703798e-01,NaN,0.065181,4.565249e-01,0.106062,0.327473,0.191946
1,endometrial,0.824775,NaN,0.936116,3.499895e-02,0.264571,0.030133,3.175433e-03,NaN,0.287843,...,0.654079,0.781930,7.278204e-03,2.185463e-03,NaN,0.359389,2.029671e-01,0.556780,0.236825,0.261292
2,luad,0.778949,NaN,0.433724,NaN,NaN,0.131262,7.607273e-12,0.065583,0.003088,...,NaN,0.000012,5.299375e-16,2.143507e-05,NaN,0.574093,2.386150e-08,0.000360,0.000060,0.000002
3,hnscc,0.988560,0.446635,0.252807,6.755440e-02,0.118225,0.011762,7.665152e-01,0.000098,NaN,...,NaN,0.005881,3.638297e-01,8.984708e-06,NaN,0.001435,1.751749e-04,0.934953,0.090658,0.795908
4,lscc,0.169387,NaN,0.610199,2.377650e-12,0.156933,0.030961,1.035001e-01,0.300931,NaN,...,0.000682,0.000139,6.967096e-08,6.784408e-12,NaN,0.005178,8.362345e-02,0.008578,0.011934,0.000571

In [13]:
perm_df = pd.read_csv("full_10k_permutation.csv")

In [14]:
perm_df

,Cancer,A1BG,A1CF,A2M,A2ML1,A4GALT,AAAS,AACS,AADAC,AADAT,...,ZSWIM9,ZW10,ZWILCH,ZWINT,ZXDA,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
0,ccrcc,0.052810,0.000838,0.029716,NaN,0.337474,0.728086,6.413643e-02,0.350422,0.057700,...,NaN,1.506673e-01,3.202242e-02,1.603670e-01,NaN,0.033585,5.243498e-01,8.419726e-02,3.727352e-01,0.202787
1,en,0.781720,NaN,0.911887,1.389663e-02,0.332572,0.005615,6.073417e-09,NaN,0.309108,...,0.601641,7.465966e-01,7.258794e-06,5.565692e-09,NaN,0.285104,8.265039e-02,5.077769e-01,2.323887e-01,0.196638
2,luad,0.758399,NaN,0.010615,NaN,NaN,0.139531,1.567981e-36,0.022448,0.017033,...,NaN,4.054898e-10,5.038784e-20,1.490761e-05,NaN,0.577845,1.056011e-10,4.521974e-08,2.750287e-15,0.000013
3,hnscc,0.996778,0.776459,0.228337,5.558182e-04,0.040184,0.014557,8.203827e-01,0.000280,NaN,...,NaN,6.634511e-04,1.484058e-01,1.437383e-03,NaN,0.002749,8.339845e-04,8.879081e-01,1.516343e-01,0.762835
4,lscc,0.137994,NaN,0.097044,2.033188e-22,0.154022,0.008081,7.086254e-02,0.456664,NaN,...,0.001427,1.917384e-13,7.815859e-51,2.845191e-33,NaN,0.011741,7.526734e-03,3.401658e-09,1.794113e-06,0.018557

In [15]:
p_val.corrwith(perm_df, axis = 1)

0    0.942944
1    0.967711
2    0.967378
3    0.971085
4    0.961925
dtype: float64

In [ ]:
#use permutations from now on
#add 2d scatterplot zooming in on bottom portion
#look at gene sets