In [26]:
import pandas as pd
import statistics as st

In [27]:
df = pd.read_csv('proteins_29.csv')

In [28]:
df = df.drop(columns=["Protein ID","Gene ID"])

In [29]:
df = df.set_index("Gene name")

In [30]:
df = df.apply(pd.to_numeric)

In [31]:
df

,Adrenal gland,Appendix,Brain,Colon,Duodenum,Endometrium,Esophagus,Fallopian tube,Fat,Gallbladder,...,Rectum,Salivary gland,Small intestine,Smooth muscle,Spleen,Stomach,Testis,Thyroid,Tonsil,Urinary bladder
Gene name,,,,,,,,,,,,,,,,,,,,,
KRT75,0,56370,786,1898,5290,411,7012,0,0,9879,...,4268,0,1458,7317,5171,7483,7261,0,236,0
KRT13,15098,47852,13851,25481,113977,31660,53921359,127494,728370,77300,...,65046,165360,33909,41044,199633,22034,30857,4551,16130413,15345978
KRT81,0,1924,0,0,0,0,0,3620,0,0,...,0,2752,3806,14264,0,19702,6699,0,0,0
KRT77,24471,117177,243,7336,23824,8656,6392,30046,4630,52560,...,1555,567,1451,5272,3921,1355,596,52664,181,13585
ARF5,546528,1053639,1259820,1061232,1418222,634573,606870,1063595,521340,532015,...,674083,284683,1847049,231428,295042,1770239,479741,364745,266700,689679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PTPN11,553922,220983,1549076,151099,709819,534201,547620,239011,564348,386733,...,469465,266472,401881,1147101,403329,423906,296896,294839,81480,336581
FBXO27,0,0,1005,0,0,0,0,0,0,0,...,0,668,0,0,0,0,0,0,0,0
SIRT2,127668,31587,7805497,43917,121987,64422,156445,47813,156607,73341,...,74128,131493,82269,105591,49574,128271,34901,124689,15379,33364
ENAH,194482,125160,509790,115268,310270,428753,459788,186494,100808,415350,...,472829,138813,248018,209227,281794,237714,288809,56249,11823,228676
E2F2,0,0,0,63,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
genes = df.index

In [33]:
stdev_list = []
mean_list = []

In [34]:
for gene in genes:
    if not isinstance(gene, str):
        continue
    if len(df.loc[gene]) != 29:
        continue
    stdev_list.append([st.stdev(df.loc[gene]),gene])
    mean_list.append([sum(df.loc[gene]) / len(df.loc[gene]),gene])

In [41]:
final_stdev = sorted(stdev_list)

In [42]:
final_mean = sorted(mean_list)

In [43]:
most_variable = final_stdev[11847:]

In [44]:
high_variability = []
for gene in most_variable:
    high_variability.append(gene[1])

In [45]:
least_variable = final_stdev[:500]
low_variability = []
for gene in least_variable:
    low_variability.append(gene[1])

In [46]:
high_expression = final_mean[11847:]
low_expression = final_mean[:500]

In [47]:
final_high_expression = []
for gene in high_expression:
    final_high_expression.append(gene[1])
final_low_expression = []
for gene in low_expression:
    final_low_expression.append(gene[1])