In [1]:
import cptac
import numpy as np
import pandas as pd
import statsmodels.stats.multitest as ssm

In [2]:
perm_df = pd.read_csv("data/full_10k_permutation_corrected.csv")
perm_df

,Cancer,A1BG,A1CF,A2M,A2ML1,A4GALT,AAAS,AACS,AADAC,AADAT,...,ZSWIM9,ZW10,ZWILCH,ZWINT,ZXDA,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
0,ccrcc,0.146442,0.004995,0.095512,NaN,0.532265,0.851988,1.691592e-01,0.545156,0.156638,...,NaN,3.098461e-01,1.010117e-01,3.231642e-01,NaN,0.104305,7.044145e-01,2.069261e-01,5.672603e-01,0.378694
1,en,0.883318,NaN,0.953553,5.628600e-02,0.543085,0.027277,1.438315e-07,NaN,0.517563,...,0.769929,8.608802e-01,8.894419e-05,1.330422e-07,NaN,0.491506,2.125946e-01,6.985013e-01,4.283120e-01,0.383779
2,luad,0.801031,NaN,0.019206,NaN,NaN,0.191032,5.371135e-35,0.037629,0.029363,...,NaN,2.594465e-09,7.619459e-19,4.915995e-05,NaN,0.641317,7.220021e-10,2.219300e-07,2.915594e-14,0.000043
3,hnscc,0.998985,0.862365,0.381438,3.371964e-03,0.103999,0.046917,8.900750e-01,0.001904,NaN,...,NaN,3.904316e-03,2.797887e-01,7.448440e-03,NaN,0.012482,4.719306e-03,9.340559e-01,2.842001e-01,0.854269
4,lscc,0.183336,NaN,0.133999,2.266058e-21,0.202066,0.014338,1.012628e-01,0.522300,NaN,...,0.002938,1.262976e-12,2.357531e-49,5.104002e-32,NaN,0.020118,1.345127e-02,1.587683e-08,6.037113e-06,0.030463

In [3]:
delta_corr_df = pd.read_csv('data/corr_diff.csv')
delta_corr_df

,Cancer,A1BG,A1CF,A2M,A2ML1,A4GALT,AAAS,AACS,AADAC,AADAT,...,ZSWIM9,ZW10,ZWILCH,ZWINT,ZXDA,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
0,ccrcc,-0.388745,0.146993,-0.277035,NaN,-0.795957,-0.044291,-0.128218,1.196756,-0.174925,...,NaN,0.269728,0.329727,-0.337301,NaN,0.337470,0.109414,-0.223934,-0.138352,-0.220727
1,endometrial,0.061654,NaN,-0.025535,0.402210,0.399061,0.663703,0.593777,NaN,0.302879,...,0.177842,0.088061,0.759429,1.006282,NaN,-0.267078,0.400272,0.147305,0.367791,0.342423
2,luad,-0.039149,NaN,0.097233,NaN,NaN,0.206094,0.683092,-0.119746,0.630155,...,NaN,0.557832,0.904669,0.645076,NaN,0.087794,0.707991,0.472139,0.418589,0.661323
3,hnscc,-0.002651,0.407295,-0.194186,0.117838,0.555675,0.462864,0.024965,-0.333934,-0.294627,...,1.039965,0.395189,0.119698,1.079145,NaN,0.591841,-0.453269,-0.010672,0.255505,-0.060708
4,lscc,0.196946,NaN,-0.062630,0.649123,0.246831,0.304418,0.150665,-0.068258,NaN,...,0.613891,0.491043,0.646430,0.838981,NaN,0.332350,0.231167,0.315679,0.268239,0.446553

In [4]:
perm_df = perm_df.melt(id_vars='Cancer', var_name = 'Gene', value_name = 'pval')
delta_corr_df = delta_corr_df.melt(id_vars='Cancer', var_name='Gene', value_name='delta_corr')

In [5]:
df = pd.merge(perm_df, delta_corr_df)
df = df.dropna()
df

      Cancer   Gene      pval  delta_corr
0      ccrcc   A1BG  0.146442   -0.388745
1       luad   A1BG  0.801031   -0.039149
2      hnscc   A1BG  0.998985   -0.002651
3       lscc   A1BG  0.183336    0.196946
4      ccrcc   A1CF  0.004995    0.146993
...      ...    ...       ...         ...
54671   lscc  ZZEF1  0.000006    0.268239
54672  ccrcc   ZZZ3  0.378694   -0.220727
54673   luad   ZZZ3  0.000043    0.661323
54674  hnscc   ZZZ3  0.854269   -0.060708
54675   lscc   ZZZ3  0.030463    0.446553

[43001 rows x 4 columns]

In [6]:
background_genes = list(pd.unique(df.Gene))

In [7]:
sig_perm_df = df[df.pval <= 0.05]

In [8]:
sig_genes = pd.DataFrame(sig_perm_df.groupby('Gene').size())
sig_genes = sig_genes[sig_genes[0] > 2]
sig_genes = list(sig_genes.index)
avg_pvals = []
avg_corrs = []
abs_avg_corrs = []
for gene in sig_genes:
    gene_df = sig_perm_df[sig_perm_df.Gene==gene]
    avg_pval = np.average(gene_df.pval)
    avg_corr = np.average(gene_df.delta_corr)
    avg_corrs.append(avg_corr)
    avg_pvals.append(avg_pval)
    abs_avg_corrs.append(abs(avg_corr))
sig_genes = pd.DataFrame({'Gene': sig_genes, 'avg_pval': avg_pvals, 'avg_delta_corr': avg_corrs, 'abs_delta_corr': abs_avg_corrs})
sig_genes

         Gene      avg_pval  avg_delta_corr  abs_delta_corr
0       AAGAB  1.191913e-05        0.513239        0.513239
1        AAK1  2.187208e-09        0.539893        0.539893
2        AAMP  7.805338e-03        0.422332        0.422332
3        AARS  1.022777e-02        0.443220        0.443220
4       AARS2  1.766085e-05        0.563538        0.563538
...       ...           ...             ...             ...
3044     ZPR1  4.507710e-03        0.552338        0.552338
3045  ZSCAN18  9.995611e-03        0.461501        0.461501
3046     ZW10  1.301439e-03        0.481355        0.481355
3047    ZWINT  2.499200e-03        0.854401        0.854401
3048   ZYG11B  6.056860e-03        0.161963        0.161963

[3049 rows x 4 columns]

In [9]:
sig_genes = sig_genes.sort_values('avg_pval')
pval_ranked_gene_list = list(sig_genes.Gene)
sig_genes = sig_genes.sort_values('abs_delta_corr', ascending = False)
delta_corr_ranked_gene_list = list(sig_genes.Gene)
down_reg = sig_genes[sig_genes.avg_delta_corr < 0]
down_reg = down_reg.sort_values('avg_delta_corr')
down_reg_ranked_list = list(down_reg.Gene)

In [10]:
from gprofiler import GProfiler
gp = GProfiler(return_dataframe=True)

In [11]:
pval_results_df = gp.profile(organism='hsapiens', query = pval_ranked_gene_list, no_iea=True,
                       ordered=True, no_evidences=False, background= background_genes)

In [12]:
delta_corr_results_df = gp.profile(organism='hsapiens', query = delta_corr_ranked_gene_list, no_iea=True,
                       ordered=True, no_evidences=False, background= background_genes)

In [13]:
down_reg_results_df = gp.profile(organism='hsapiens', query = down_reg_ranked_list, no_iea=True,
                       ordered=True, no_evidences=False, background= background_genes)

In [14]:
pval_filtered_results = pval_results_df[pval_results_df.term_size <= 500]
pval_filtered_results = pval_filtered_results[pval_filtered_results.term_size >=5]
delta_corr_filtered_results = delta_corr_results_df[delta_corr_results_df.term_size <= 500]
delta_corr_filtered_results = delta_corr_filtered_results[delta_corr_filtered_results.term_size >=5]
down_reg_filtered_results = down_reg_results_df[down_reg_results_df.term_size <= 500]
down_reg_filtered_results = down_reg_filtered_results[down_reg_filtered_results.term_size >=5]

In [15]:
pval_kegg_results = pval_filtered_results[pval_filtered_results.source == 'KEGG']
pval_kegg_results

,source,native,name,p_value,significant,description,term_size,query_size,intersection_size,effective_domain_size,precision,recall,query,parents,intersections,evidences
219,KEGG,KEGG:00280,"Valine, leucine and isoleucine degradation",0.000101,True,"Valine, leucine and isoleucine degradation",48,2397,24,12939,0.010013,0.500000,query_1,[KEGG:00000],"[ALDH6A1, OXCT1, ACAT1, IL4I1, ALDH7A1, MUT, D...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
232,KEGG,KEGG:01200,Carbon metabolism,0.000552,True,Carbon metabolism,112,2596,45,12939,0.017334,0.401786,query_1,[KEGG:00000],"[ALDH6A1, ALDOC, ACAT1, PKM, RPIA, PFKM, RGN, ...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
240,KEGG,KEGG:00240,Pyrimidine metabolism,0.001212,True,Pyrimidine metabolism,51,2738,27,12939,0.009861,0.529412,query_1,[KEGG:00000],"[CAD, ENTPD1, TK1, NME1, UPP1, TYMS, CMPK2, CA...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
255,KEGG,KEGG:01230,Biosynthesis of amino acids,0.003258,True,Biosynthesis of amino acids,72,2757,32,12939,0.011607,0.444444,query_1,[KEGG:00000],"[ALDOC, PKM, RPIA, PFKM, ASS1, PGAM1, PFKP, EN...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
260,KEGG,KEGG:01240,Biosynthesis of cofactors,0.004217,True,Biosynthesis of cofactors,136,2808,56,12939,0.019943,0.411765,query_1,[KEGG:00000],"[FLAD1, TPK1, GCLC, AK4, CAD, ALPL, PKM, NADK2...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
261,KEGG,KEGG:00270,Cysteine and methionine metabolism,0.004425,True,Cysteine and methionine metabolism,46,1564,17,12939,0.010870,0.369565,query_1,[KEGG:00000],"[GCLC, SMS, MTAP, IL4I1, TST, MPST, DNMT3A, LD...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
265,KEGG,KEGG:00920,Sulfur metabolism,0.005339,True,Sulfur metabolism,10,1618,7,12939,0.004326,0.700000,query_1,[KEGG:00000],"[TST, MPST, PAPSS2, SUOX, SELENBP1, ETHE1, IMP...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
307,KEGG,KEGG:00010,Glycolysis / Gluconeogenesis,0.018440,True,Glycolysis / Gluconeogenesis,62,565,11,12939,0.019469,0.177419,query_1,[KEGG:00000],"[ALDOC, PKM, PFKM, ALDH7A1, PGAM1, PFKP, LDHB,...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
316,KEGG,KEGG:03030,DNA replication,0.022233,True,DNA replication,34,605,8,12939,0.013223,0.235294,query_1,[KEGG:00000],"[RFC5, PRIM1, MCM5, MCM6, POLA2, LIG1, POLD2, ...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
317,KEGG,KEGG:00640,Propanoate metabolism,0.022739,True,Propanoate metabolism,34,2725,17,12939,0.006239,0.500000,query_1,[KEGG:00000],"[ALDH6A1, ACAT1, LDHB, LDHA, MUT, DBT, ABAT, A...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
318,KEGG,KEGG:00740,Riboflavin metabolism,0.023263,True,Riboflavin metabolism,8,33,2,12939,0.060606,0.250000,query_1,[KEGG:00000],"[FLAD1, ACP5]","[[KEGG], [KEGG]]"
333,KEGG,KEGG:00250,"Alanine, aspartate and glutamate metabolism",0.032579,True,"Alanine, aspartate and glutamate metabolism",32,951,10,12939,0.010515,0.312500,query_1,[KEGG:00000],"[CAD, PPAT, IL4I1, ASS1, GFPT1, GPT2, ALDH5A1,...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
337,KEGG,KEGG:04110,Cell cycle,0.035798,True,Cell cycle,111,494,14,12939,0.028340,0.126126,query_1,[KEGG:00000],"[CHEK2, CCNA2, CDK2, CDK6, MCM5, SMAD4, TP53, ...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."

In [16]:
delta_corr_kegg_results = delta_corr_filtered_results[delta_corr_filtered_results.source == 'KEGG']
delta_corr_kegg_results

,source,native,name,p_value,significant,description,term_size,query_size,intersection_size,effective_domain_size,precision,recall,query,parents,intersections,evidences
236,KEGG,KEGG:03030,DNA replication,0.000005,True,DNA replication,34,1072,15,12939,0.013993,0.441176,query_1,[KEGG:00000],"[RFC5, PRIM1, MCM7, MCM5, MCM2, MCM4, RFC1, PO...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
239,KEGG,KEGG:03430,Mismatch repair,0.000007,True,Mismatch repair,22,1072,12,12939,0.011194,0.545455,query_1,[KEGG:00000],"[PMS2, RFC5, RFC1, MSH6, LIG1, RFC4, MSH3, RFC...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
258,KEGG,KEGG:04110,Cell cycle,0.000020,True,Cell cycle,111,433,18,12939,0.041570,0.162162,query_1,[KEGG:00000],"[CHEK1, CCNA2, PLK1, TP53, CHEK2, YWHAG, CCNB1...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
303,KEGG,KEGG:00280,"Valine, leucine and isoleucine degradation",0.000340,True,"Valine, leucine and isoleucine degradation",48,2964,26,12939,0.008772,0.541667,query_1,[KEGG:00000],"[OXCT1, IL4I1, ALDH7A1, ALDH3A2, ACAD8, HMGCS1...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
344,KEGG,KEGG:00240,Pyrimidine metabolism,0.001960,True,Pyrimidine metabolism,51,2632,26,12939,0.009878,0.509804,query_1,[KEGG:00000],"[TYMS, TK1, CAD, DTYMK, DCTPP1, UMPS, UCK2, CT...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
361,KEGG,KEGG:01230,Biosynthesis of amino acids,0.003144,True,Biosynthesis of amino acids,72,2890,33,12939,0.011419,0.458333,query_1,[KEGG:00000],"[PGK1, RPIA, CPS1, PGAM1, PSPH, PYCR2, ARG2, P...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
406,KEGG,KEGG:00970,Aminoacyl-tRNA biosynthesis,0.007731,True,Aminoacyl-tRNA biosynthesis,28,805,11,12939,0.013665,0.392857,query_1,[KEGG:00000],"[DARS2, TARS2, SEPSECS, HARS2, YARS2, WARS2, N...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
425,KEGG,KEGG:01240,Biosynthesis of cofactors,0.011269,True,Biosynthesis of cofactors,136,2975,57,12939,0.019160,0.419118,query_1,[KEGG:00000],"[FLAD1, CAD, NADK2, GCLC, HMBS, UMPS, UROD, UG...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
463,KEGG,KEGG:01200,Carbon metabolism,0.019601,True,Carbon metabolism,112,2975,45,12939,0.015126,0.401786,query_1,[KEGG:00000],"[PGK1, RPIA, CPS1, PGAM1, PSPH, GPI, TKFC, PFK...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
494,KEGG,KEGG:03013,RNA transport,0.031887,True,RNA transport,152,735,23,12939,0.031293,0.151316,query_1,[KEGG:00000],"[STRAP, GEMIN2, EIF5B, XPO5, PAIP1, CLNS1A, EI...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
502,KEGG,KEGG:03420,Nucleotide excision repair,0.035977,True,Nucleotide excision repair,44,1072,12,12939,0.011194,0.272727,query_1,[KEGG:00000],"[GTF2H1, RFC5, CUL4A, RAD23B, ERCC4, RFC1, LIG...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."

In [17]:
down_reg_kegg_results = down_reg_filtered_results[down_reg_filtered_results.source == 'KEGG']
down_reg_kegg_results

,source,native,name,p_value,significant,description,term_size,query_size,intersection_size,effective_domain_size,precision,recall,query,parents,intersections,evidences
4,KEGG,KEGG:00910,Nitrogen metabolism,0.009448,True,Nitrogen metabolism,14,13,2,12939,0.153846,0.142857,query_1,[KEGG:00000],"[CA4, CA3]","[[KEGG], [KEGG]]"
10,KEGG,KEGG:00190,Oxidative phosphorylation,0.029291,True,Oxidative phosphorylation,116,34,4,12939,0.117647,0.034483,query_1,[KEGG:00000],"[NDUFS4, NDUFS1, ATP6V1H, ATP6V1G1]","[[KEGG], [KEGG], [KEGG], [KEGG]]"
13,KEGG,KEGG:00130,Ubiquinone and other terpenoid-quinone biosynt...,0.034157,True,Ubiquinone and other terpenoid-quinone biosynt...,9,38,2,12939,0.052632,0.222222,query_1,[KEGG:00000],"[COQ5, COQ6]","[[KEGG], [KEGG]]"

Make KEGG Mapper scripts
https://www.kegg.jp/kegg/tool/map_pathway2.html
Search mode: 
    organism-specific: hsa
    outside ID: UniProt

In [18]:
for index, row in pval_kegg_results.iterrows():
    pathway = row.description
    print('\n' + str(pathway))
    old_genes = (row.intersections)
    new_genes = list(gp.convert(query = old_genes, organism = 'hsapiens', target_namespace= 'uniprotswissprot_acc').converted)
    for gene, ID in zip(old_genes, new_genes):
        s = ID
        delta_corr = list(sig_genes[sig_genes.Gene == gene].avg_delta_corr)[0]
        if delta_corr > 0:
            s += ' green'
        else:
            s+= ' red'
        print(s)

Valine, leucine and isoleucine degradation
Q02252 green
P55809 green
P24752 green
Q96RQ9 green
P49419 green
P22033 green
P11182 green
P26440 green
P80404 green
P16219 green
Q9UKU7 green
Q06278 green
P45954 green
Q6NVY1 green
P35914 green
P42765 green
P11310 green
Q96RQ3 green
P30084 green
P31937 green
P51648 green
Q01581 green
P05165 green
Q99714 green

Carbon metabolism
Q02252 green
P09972 green
P24752 green
P14618 green
P49247 green
P08237 green
Q15493 green
P18669 green
Q01813 green
P10768 green
P13929 green
Q8TD30 green
P60174 green
Q5T6J7 green
P78330 green
P22033 green
P36957 green
P11498 green
P17174 green
P11413 green
P16219 green
P00558 green
Q9P2R7 green
P34896 green
P48735 green
Q6NVY1 green
Q9Y617 green
P04075 green
P07954 green
P17858 green
Q3LXA3 green
P06744 green
P08559 green
P30084 green
O43175 green
P00367 green
P23378 green
P09467 red
P53597 red
P31327 green
P05165 green
P19367 green
P20132 green
O75390 green
P06733 green

Pyrimidine metabolism
P27708 green
P49961 green
P04183 green
P15531 green
Q16831 green
P04818 green
Q5EBM0 green
Q8WVQ1 green
Q9BZX2 green
P49902 green
P11172 green
Q9H0P0 green
P31350 green
Q9BXI3 red
P00491 green
P33316 green
Q9Y5B8 green
Q96BW1 green
P19971 green
P32321 green
P23919 green
Q9NRF8 green
Q02127 green
P17812 green
Q9H773 green
P27707 green
P30085 green

Biosynthesis of amino acids
P09972 green
P14618 green
P49247 green
P08237 green
P00966 green
P18669 green
Q01813 green
P13929 green
Q8TD30 green
P60174 green
Q03154 green
P78330 green
P11498 green
P17174 green
P00558 green
Q9NZL9 green
P34896 green
P48735 green
Q9Y617 green
P04075 green
P17858 green
P32322 green
P78540 green
P54886 green
Q96C36 green
O43175 green
P31327 green
P20132 green
O75390 green
P06733 green
P08243 green
P05089 red

Biosynthesis of cofactors
Q8NFF5 green
Q9H3S4 green
P48506 green
P27144 green
P27708 green
P05186 green
P14618 green
Q4G0N4 green
Q15493 green
P15531 green
P22830 green
Q9Y697 green
P00568 green
Q5EBM0 green
P30520 green
P11172 green
Q9UIJ7 green
P34949 green
P08397 green
P19224 green
Q9HAN9 green
P48507 green
Q9NZJ6 green
Q9NZL9 green
P34896 green
Q5HYK3 red
P13995 green
P15559 green
Q92820 green
Q8N3Y7 green
Q9Y617 green
P36551 green
Q05932 green
P30566 green
P13716 green
P08236 green
Q9Y5B8 green
Q03393 green
Q969G6 green
Q9NWU1 green
Q6IA69 green
P30793 green
P51648 green
P14902 green
P11586 green
Q9NRF8 green
Q02127 green
P17812 green
Q96T66 green
Q9Y2Z9 red
Q9BZ23 green
Q9Y3D8 green
P30085 green
P06132 green
Q6XQN6 green
Q6UB35 green

Cysteine and methionine metabolism
P48506 green
P52788 green
Q13126 green
Q96RQ9 green
Q16762 green
P25325 green
Q9Y6K1 green
P07195 green
P00338 green
Q96HN2 green
P17174 green
P26358 green
Q9UHY7 green
P48507 green
Q9NZL9 green
O43865 green
Q9Y617 green

Sulfur metabolism
Q16762 green
P25325 green
O95340 green
P51687 green
Q13228 red
O95571 green
Q9NX62 green

Glycolysis / Gluconeogenesis
P09972 green
P14618 green
P08237 green
P49419 green
P18669 green
Q01813 green
P07195 green
P13929 green
P00325 red
P00338 green
P60174 green

DNA replication
P40937 green
P49642 green
P33992 green
Q14566 green
Q14181 green
P18858 green
P49005 green
P33993 green

Propanoate metabolism
Q02252 green
P24752 green
P07195 green
P00338 green
P22033 green
P11182 green
P80404 green
P16219 green
Q9P2R7 green
Q6NVY1 green
O95822 green
P30084 green
P53597 red
P05165 green
Q9H6R3 green
Q13085 green
P21953 green

Riboflavin metabolism
Q8NFF5 green
P13686 red

Alanine, aspartate and glutamate metabolism
P27708 green
Q06203 green
Q96RQ9 green
P00966 green
Q06210 green
Q8TD30 green
P51649 green
P17174 green
P30520 green
P80404 green

Cell cycle
O96017 green
P20248 green
P24941 green
Q00534 green
P33992 green
Q13485 green
P04637 green
P61981 green
Q14566 green
O60566 green
Q04917 green
P53350 green
Q13257 green
P14635 green

In [21]:
cancer_list = [ccrcc,en,luad,hnscc,lscc]
cancer_names = ['ccrcc', 'en', 'luad', 'hnscc', 'lscc']

In [22]:
delta_corr_kegg_results

,source,native,name,p_value,significant,description,term_size,query_size,intersection_size,effective_domain_size,precision,recall,query,parents,intersections,evidences
236,KEGG,KEGG:03030,DNA replication,0.000005,True,DNA replication,34,1072,15,12939,0.013993,0.441176,query_1,[KEGG:00000],"[RFC5, PRIM1, MCM7, MCM5, MCM2, MCM4, RFC1, PO...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
239,KEGG,KEGG:03430,Mismatch repair,0.000007,True,Mismatch repair,22,1072,12,12939,0.011194,0.545455,query_1,[KEGG:00000],"[PMS2, RFC5, RFC1, MSH6, LIG1, RFC4, MSH3, RFC...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
258,KEGG,KEGG:04110,Cell cycle,0.000020,True,Cell cycle,111,433,18,12939,0.041570,0.162162,query_1,[KEGG:00000],"[CHEK1, CCNA2, PLK1, TP53, CHEK2, YWHAG, CCNB1...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
303,KEGG,KEGG:00280,"Valine, leucine and isoleucine degradation",0.000340,True,"Valine, leucine and isoleucine degradation",48,2964,26,12939,0.008772,0.541667,query_1,[KEGG:00000],"[OXCT1, IL4I1, ALDH7A1, ALDH3A2, ACAD8, HMGCS1...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
344,KEGG,KEGG:00240,Pyrimidine metabolism,0.001960,True,Pyrimidine metabolism,51,2632,26,12939,0.009878,0.509804,query_1,[KEGG:00000],"[TYMS, TK1, CAD, DTYMK, DCTPP1, UMPS, UCK2, CT...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
361,KEGG,KEGG:01230,Biosynthesis of amino acids,0.003144,True,Biosynthesis of amino acids,72,2890,33,12939,0.011419,0.458333,query_1,[KEGG:00000],"[PGK1, RPIA, CPS1, PGAM1, PSPH, PYCR2, ARG2, P...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
406,KEGG,KEGG:00970,Aminoacyl-tRNA biosynthesis,0.007731,True,Aminoacyl-tRNA biosynthesis,28,805,11,12939,0.013665,0.392857,query_1,[KEGG:00000],"[DARS2, TARS2, SEPSECS, HARS2, YARS2, WARS2, N...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
425,KEGG,KEGG:01240,Biosynthesis of cofactors,0.011269,True,Biosynthesis of cofactors,136,2975,57,12939,0.019160,0.419118,query_1,[KEGG:00000],"[FLAD1, CAD, NADK2, GCLC, HMBS, UMPS, UROD, UG...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
463,KEGG,KEGG:01200,Carbon metabolism,0.019601,True,Carbon metabolism,112,2975,45,12939,0.015126,0.401786,query_1,[KEGG:00000],"[PGK1, RPIA, CPS1, PGAM1, PSPH, GPI, TKFC, PFK...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
494,KEGG,KEGG:03013,RNA transport,0.031887,True,RNA transport,152,735,23,12939,0.031293,0.151316,query_1,[KEGG:00000],"[STRAP, GEMIN2, EIF5B, XPO5, PAIP1, CLNS1A, EI...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."
502,KEGG,KEGG:03420,Nucleotide excision repair,0.035977,True,Nucleotide excision repair,44,1072,12,12939,0.011194,0.272727,query_1,[KEGG:00000],"[GTF2H1, RFC5, CUL4A, RAD23B, ERCC4, RFC1, LIG...","[[KEGG], [KEGG], [KEGG], [KEGG], [KEGG], [KEGG..."

In [23]:

gene_ids = []
txt = ''
for index, row in delta_corr_kegg_results.iterrows():
    pathway = row.description
    
    old_genes = (row.intersections)
    print(old_genes)
    slopes_df = rc.calculate_regression(cancer_list, old_genes, cancer_names)
    print('\n' + str(pathway))
    print(slopes_df)
    new_genes = list(gp.convert(query = old_genes, organism = 'hsapiens', target_namespace= 'uniprotswissprot_acc').converted)
    for gene, ID in zip(old_genes, new_genes):
        s = ID
        gene_df = slopes_df[slopes_df.gene == gene]
        avg_slope = np.mean(gene_df.interaction_coeff)
        if avg_slope > 0:
            s += ' green'
        else:
            s+= ' red'
        txt += s + '\n'

['RFC5', 'PRIM1', 'MCM7', 'MCM5', 'MCM2', 'MCM4', 'RFC1', 'POLA2', 'LIG1', 'RFC4', 'MCM6', 'RFC3', 'SSBP1', 'POLD2', 'POLD3']

cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)

cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)

ccrcc
RFC5
PRIM1
MCM7
MCM5
MCM2
MCM4
RFC1
POLA2
LIG1
RFC4
MCM6
RFC3
SSBP1
POLD2
POLD3
en
RFC5
PRIM1
MCM7
MCM5
MCM2
MCM4
RFC1
POLA2
LIG1
RFC4
MCM6
RFC3
SSBP1
POLD2
POLD3
luad
RFC5
PRIM1
MCM7
MCM5
MCM2
MCM4
RFC1
POLA2
LIG1
RFC4
MCM6
RFC3
SSBP1
POLD2
POLD3
hnscc
RFC5
PRIM1
MCM7
MCM5
MCM2
MCM4
RFC1
POLA2
LIG1
RFC4
MCM6
RFC3
SSBP1
POLD2
POLD3
lscc
RFC5
PRIM1
MCM7
MCM5
MCM2
MCM4
RFC1
POLA2
LIG1
RFC4
MCM6
RFC3
SSBP1
POLD2
POLD3

DNA replication
     gene cancer  interaction_coeff  condition_coeff  transcript_coeff  \
0    RFC5  ccrcc          -0.043390         0.446613          0.061585
1   PRIM1  ccrcc           0.036482         0.411458         -0.001128
2    MCM7  ccrcc          -0.015694         1.019508          0.045208
3    MCM5  ccrcc          -0.045800         0.894918          0.090340
4    MCM2  ccrcc          -0.039351         1.055137          0.088322
..    ...    ...                ...              ...               ...
10   MCM6   lscc           2.012947       -33.505771          0.126389
11   RFC3   lscc           1.007726       -15.742462         -0.229781
12  SSBP1   lscc           2.526943       -43.768370         -0.779431
13  POLD2   lscc           0.673479       -11.811183          0.277750
14  POLD3   lscc           1.286471       -20.427045          0.346120

    intercept  interaction_pval  condition_pval  transcript_pval  \
0   -0.433473          0.049659    6.715109e-04         0.003201
1   -0.382691          0.640052    1.334458e-02         0.980581
2   -1.165363          0.662331    1.578294e-04         0.098216
3   -1.175187          0.311647    8.036796e-05         0.017467
4   -1.052501          0.566878    4.216188e-10         0.072586
..        ...               ...             ...              ...
10  -5.851948          0.000004    9.633485e-06         0.836973
11   2.725751          0.000137    2.543813e-04         0.836973
12  12.667787          0.001257    1.292928e-03         0.836973
13  -5.554126          0.036907    3.700180e-02         0.836973
14  -7.505188          0.002169    4.131294e-03         0.836973

    intercept_pval
0     3.095094e-04
1     4.900774e-03
2     3.368693e-06
3     2.801189e-08
4     8.166463e-12
..             ...
10    9.516768e-01
11    9.516768e-01
12    9.516768e-01
13    9.516768e-01
14    9.516768e-01

[75 rows x 10 columns]
['PMS2', 'RFC5', 'RFC1', 'MSH6', 'LIG1', 'RFC4', 'MSH3', 'RFC3', 'MSH2', 'SSBP1', 'POLD2', 'POLD3']

cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)

cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)

ccrcc
PMS2
RFC5
RFC1
MSH6
LIG1
RFC4
MSH3
RFC3
MSH2
SSBP1
POLD2
POLD3
en
PMS2
RFC5
RFC1
MSH6
LIG1
RFC4
MSH3
RFC3
MSH2
SSBP1
POLD2
POLD3
luad
PMS2
RFC5
RFC1
MSH6
LIG1
RFC4
MSH3
RFC3
MSH2
SSBP1
POLD2
POLD3
hnscc
PMS2
RFC5
RFC1
MSH6
LIG1
RFC4
MSH3
RFC3
MSH2
SSBP1
POLD2
POLD3
lscc
PMS2
RFC5
RFC1
MSH6
LIG1
RFC4
MSH3
RFC3
MSH2
SSBP1
POLD2
POLD3

Mismatch repair
     gene cancer  interaction_coeff  condition_coeff  transcript_coeff  \
0    PMS2  ccrcc           0.000794        -0.121777          0.024171
1    RFC5  ccrcc          -0.043390         0.446613          0.061585
2    RFC1  ccrcc           0.001244        -0.048388          0.013927
3    MSH6  ccrcc          -0.061074         0.777337          0.106847
4    LIG1  ccrcc          -0.129574         0.831057          0.181179
5    RFC4  ccrcc          -0.068957         0.455625          0.087354
6    MSH3  ccrcc           0.032595        -0.400533         -0.001073
7    RFC3  ccrcc          -0.083975         0.322909          0.118123
8    MSH2  ccrcc          -0.037585         0.455130          0.072196
9   SSBP1  ccrcc           0.005566        -0.333080          0.007627
10  POLD2  ccrcc           0.022474        -0.112340         -0.012361
11  POLD3  ccrcc           0.038263        -0.047117         -0.004188
0    PMS2     en           0.872686        -9.234108         -0.383943
1    RFC5     en           0.443203        -4.015793          0.155960
2    RFC1     en           1.287258       -15.391127         -0.723350
3    MSH6     en           0.517577        -5.796562          0.414309
4    LIG1     en           0.336736        -3.126533          0.486529
5    RFC4     en           0.225774        -2.025932          0.232771
6    MSH3     en           1.285798       -13.691078         -0.405567
7    RFC3     en           0.266031        -2.670189          0.045891
8    MSH2     en           0.263409        -2.963589          0.191138
9   SSBP1     en           1.068610       -11.162575         -0.352263
10  POLD2     en           0.528843        -5.747714         -0.069256
11  POLD3     en           0.837322        -8.419227         -0.031975
0    PMS2   luad           1.939518        -5.191905         -0.685986
1    RFC5   luad           0.944283        -1.716023          0.027406
2    RFC1   luad           2.069780        -8.351884         -0.595889
3    MSH6   luad           1.994466        -6.237861          0.851810
4    LIG1   luad           2.020491        -3.800752         -0.167983
5    RFC4   luad           0.939635        -1.871392          0.093261
6    MSH3   luad           0.546894        -1.288694          0.972935
7    RFC3   luad           1.001154        -1.521844         -0.298821
8    MSH2   luad           1.091965        -2.860851          0.343063
9   SSBP1   luad           1.656539        -7.258542          0.120784
10  POLD2   luad           0.297820        -1.193882          0.390609
11  POLD3   luad           0.722106        -0.819130          1.271962
0    PMS2  hnscc           0.452257        -4.538379          0.050540
1    RFC5  hnscc           0.330784        -2.893216          0.363030
2    RFC1  hnscc           0.480796        -5.294891          0.168600
3    MSH6  hnscc           0.347140        -4.030369          0.552248
4    LIG1  hnscc           0.323613        -3.172715          0.526319
5    RFC4  hnscc           0.160687        -1.471921          0.308567
6    MSH3  hnscc           0.536001        -5.490779          0.048170
7    RFC3  hnscc           0.047185        -0.175032          0.250557
8    MSH2  hnscc           0.055138        -0.581519          0.826461
9   SSBP1  hnscc           0.399337        -4.480687          0.180822
10  POLD2  hnscc           0.012553         0.060443          0.295053
11  POLD3  hnscc          -0.036063         0.461518          0.672543
0    PMS2   lscc           1.288360       -21.280315          0.055852
1    RFC5   lscc           1.377588       -22.047313         -0.215177
2    RFC1   lscc           1.549166       -26.884683         -0.147326
3    MSH6   lscc           2.074899       -35.578757          0.416725
4    LIG1   lscc           1.643490       -26.165922          0.376402
5    RFC4   lscc           1.326649       -21.334068         -0.111382
6    MSH3   lscc           1.185864       -20.174085          0.638687
7    RFC3   lscc           1.007726       -15.742462         -0.229781
8    MSH2   lscc           1.699999       -29.073605          0.266386
9   SSBP1   lscc           2.526943       -43.768370         -0.779431
10  POLD2   lscc           0.673479       -11.811183          0.277750
11  POLD3   lscc           1.286471       -20.427045          0.346120

    intercept  interaction_pval  condition_pval  transcript_pval  \
0   -0.186612      9.256399e-01    3.537386e-01         0.004013
1   -0.433473      3.089866e-02    7.162783e-04         0.001707
2   -0.228216      9.256399e-01    7.323099e-01         0.050811
3   -1.042109      1.251055e-02    2.247397e-04         0.000020
4   -0.980491      7.362990e-03    1.233497e-05         0.000066
5   -0.441664      7.362990e-03    7.692467e-05         0.000307
6    0.039116      1.670231e-10    1.233497e-05         0.714135
7   -0.338143      7.362990e-03    8.980367e-04         0.000066
8   -0.589023      3.089866e-02    5.480659e-04         0.000044
9   -0.182530      6.971420e-01    3.537386e-01         0.480188
10   0.054000      7.362990e-03    4.831425e-01         0.130003
11  -0.044611      7.362990e-03    7.323099e-01         0.432499
0    3.891207      3.646426e-01    3.314274e-01         0.912166
1   -1.580390      3.646426e-01    3.314274e-01         0.912166
2    8.799077      3.816566e-02    4.679531e-02         0.504663
3   -5.143202      2.589982e-01    2.677785e-01         0.504663
4   -5.148540      2.630799e-01    3.074182e-01         0.322483
5   -2.137314      4.412701e-01    4.403979e-01         0.912166
6    4.270799      2.630799e-01    2.677785e-01         0.912166
7   -0.425401      3.646426e-01    3.314274e-01         0.912166
8   -2.166149      3.646426e-01    3.314274e-01         0.912166
9    3.481099      3.646426e-01    3.314274e-01         0.912166
10   0.757119      2.630799e-01    2.677785e-01         0.912166
11   0.119467      3.816566e-02    4.679531e-02         0.912166
0    1.358231      5.589876e-10    6.319327e-11         0.027188
1   -0.859125      3.747335e-03    3.178153e-02         0.925818
2    2.151703      5.004393e-06    3.871015e-05         0.235182
3   -3.997834      1.576887e-06    1.147794e-05         0.060456
4   -0.949113      5.589876e-10    7.238236e-07         0.674994
5   -1.163235      5.554588e-07    3.871015e-05         0.674994
6   -3.629583      9.750358e-02    2.648023e-01         0.006024
7    0.037095      1.632553e-03    2.744014e-02         0.429120
8   -1.808245      5.554588e-07    8.502214e-06         0.141898
9   -1.323843      1.143959e-02    2.131983e-02         0.913129
10  -1.665708      3.587160e-01    3.522669e-01         0.347691
11  -4.906081      1.497643e-01    5.797324e-01         0.027188
0   23.630559      6.696682e-02    6.593497e-02         0.782003
1   21.009244      6.696682e-02    6.593497e-02         0.010013
2   22.452823      7.715172e-02    9.591519e-02         0.549619
3   18.082628      7.715172e-02    8.038631e-02         0.003703
4   19.382069      3.031066e-02    3.100944e-02         0.000009
5   21.823156      2.064248e-01    1.792969e-01         0.006867
6   23.860652      1.308943e-02    1.590519e-02         0.782003
7   21.944801      9.220753e-01    9.717877e-01         0.139470
8   16.448529      9.220753e-01    9.641471e-01         0.000912
9   25.381103      6.805231e-02    6.593497e-02         0.384671
10  20.800181      9.358535e-01    9.717877e-01         0.079283
11  16.438949      9.220753e-01    9.641471e-01         0.000912
0   -1.257432      2.382649e-05    2.026917e-05         0.822193
1    1.959067      1.109526e-07    1.359557e-07         0.512524
2    1.808265      3.609655e-05    9.216223e-05         0.699793
3   -9.503581      2.382649e-05    2.026917e-05         0.512524
4   -7.945779      3.405009e-06    6.168946e-06         0.512524
5   -0.377724      2.063331e-07    1.359557e-07         0.699793
6  -11.356742      1.173818e-04    1.623826e-04         0.196247
7    2.725751      1.218101e-04    2.261167e-04         0.512524
8   -6.467966      1.535752e-08    1.489505e-08         0.512524
9   12.667787      1.106325e-03    1.137777e-03         0.512524
10  -5.554126      3.690718e-02    3.700180e-02         0.512524
11  -7.505188      2.208686e-03    4.206408e-03         0.512524

    intercept_pval
0     1.101366e-01
1     3.714113e-04
2     1.171569e-01
3     1.230869e-07
4     6.874942e-08
5     3.922125e-05
6     5.789357e-01
7     1.033603e-04
8     8.030731e-07
9     5.789357e-01
10    6.745153e-01
11    5.789357e-01
0     9.308004e-01
1     9.308004e-01
2     5.028817e-01
3     5.028817e-01
4     2.038891e-01
5     9.308004e-01
6     9.308004e-01
7     9.308004e-01
8     9.308004e-01
9     9.308004e-01
10    9.308004e-01
11    9.683897e-01
0     4.528189e-02
1     2.638409e-01
2     2.638409e-01
3     3.363088e-03
4     1.987525e-01
5     3.667996e-03
6     1.340874e-03
7     9.495098e-01
8     1.838184e-03
9     6.760138e-01
10    1.987525e-01
11    1.838184e-03
0     1.090736e-24
1     1.481648e-37
2     1.658202e-14
3     5.768899e-17
4     4.401968e-42
5     7.212082e-54
6     2.348157e-31
7     3.695008e-33
8     2.975223e-11
9     4.965379e-28
10    7.293297e-26
11    1.624202e-16
0     8.240608e-01
1     7.757577e-01
2     8.240608e-01
3     5.222401e-01
4     4.967015e-01
5     9.130074e-01
6     1.684457e-01
7     7.229331e-01
8     4.967015e-01
9     5.222401e-01
10    5.222401e-01
11    5.222401e-01

['CHEK1', 'CCNA2', 'PLK1', 'TP53', 'CHEK2', 'YWHAG', 'CCNB1', 'BUB1B', 'TFDP1', 'MCM7', 'MAD2L1', 'MCM5', 'MCM2', 'CDKN2A', 'MCM4', 'YWHAE', 'CDK1', 'EP300']

cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)

cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)
cptac warning: You tried to flatten a column index that didn't have multiple levels, so we didn't actually change anything. (C:\Users\nanel\anaconda3\lib\site-packages\cptac\dataset.py, line 700)

ValueError: Length mismatch: Expected axis has 3 elements, new values have 2 elements

In [ ]:
gene_ids = []
for index, row in down_reg_kegg_results.iterrows():
    pathway = row.description
    print('\n' + str(pathway))
    old_genes = (row.intersections)
    new_genes = list(gp.convert(query = old_genes, organism = 'hsapiens', target_namespace= 'uniprotswissprot_acc').converted)
    for gene, ID in zip(old_genes, new_genes):
        s = ID
        delta_corr = list(sig_genes[sig_genes.Gene == gene].avg_delta_corr)[0]
        if delta_corr > 0:
            s += ' green'
        else:
            s+= ' red'
        print(s)

In [ ]:
pval_results_df = gp.profile(organism='hsapiens', query = pval_ranked_gene_list, no_iea=True,
                       ordered=False, no_evidences=False, background= background_genes)
pval_filtered_results = pval_results_df[pval_results_df.term_size <= 500]
pval_filtered_results = pval_filtered_results[pval_filtered_results.term_size >=5]
pval_kegg_results = pval_filtered_results[pval_filtered_results.source == 'KEGG']
for index, row in pval_kegg_results.iterrows():
    pathway = row.description
    print('\n' + str(pathway))
    old_genes = (row.intersections)
    new_genes = list(gp.convert(query = old_genes, organism = 'hsapiens', target_namespace= 'uniprotswissprot_acc').converted)
    for gene, ID in zip(old_genes, new_genes):
        s = ID
        delta_corr = list(sig_genes[sig_genes.Gene == gene].avg_delta_corr)[0]
        if delta_corr > 0:
            s += ' green'
        else:
            s+= ' red'
        print(s)

In [ ]:
pval_results_df = gp.profile(organism='hsapiens', query = pval_ranked_gene_list, no_iea=True,
                       ordered=False, no_evidences=False)
pval_filtered_results = pval_results_df[pval_results_df.term_size <= 500]
pval_filtered_results = pval_filtered_results[pval_filtered_results.term_size >=5]
pval_kegg_results = pval_filtered_results[pval_filtered_results.source == 'KEGG']
for index, row in pval_kegg_results.iterrows():
    pathway = row.description
    print('\n' + str(pathway))
    old_genes = (row.intersections)
    new_genes = list(gp.convert(query = old_genes, organism = 'hsapiens', target_namespace= 'uniprotswissprot_acc').converted)
    for gene, ID in zip(old_genes, new_genes):
        s = ID
        delta_corr = list(sig_genes[sig_genes.Gene == gene].avg_delta_corr)[0]
        if delta_corr > 0:
            s += ' green'
        else:
            s+= ' red'
        print(s)